
# Closure

We finally finished our brief journey on the exploration of microbiome analysis in R. Although our data is only a few, the tutorial hopefully have demonstrated many of the steps and main options of microbial analysis you can do in R. 

We have started with the aim to analyze whether the gut microbiome changes or differ between the early and late days of post weaning (eating) period of a mice, using the data **mothur MiSeq SOP**. The analysis showed that there is a difference between in the gut microbiome composition between the early and late samples. We also knew that the gut microbiome was dominated by microbes from the phylum **Firmicutes**, and among them the microbe *Oscillibacter sp.* became the most important microbes in differentiating between the early and late aged mice using Random Forest algorithm. 

There is much more you can explore about microbiome analysis in R. There is even a new package on development also for microbiome analysis, called [`microbiome`](https://bioconductor.org/packages/devel/bioc/vignettes/microbiome/inst/doc/vignette.html). I have made a mini article about it also in [here](https://rpubs.com/nabiilahardini/microbiome), but hopefully I am able to update it to give it a more detailed touch. Even so, this book hopefully compromise a decent overview, step-by-step, from raw reads to insight, overall aspect of microbiome analysis in R.

Thank you for reading and I hope this book has been useful to you!

Keep learning and exploring!

***

# References

